### ISSUE TITLE
Broken v1.1.68

### ISSUE THREAD

**Issue by leuduan** [dynatrace-oss/api-client-python#102]
**Describe the bug**

Hi, just notice the newly published version 1.1.68 is broken.

```sh
>>> from dynatrace import Dynatrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/dynatrace/__init__.py", line 1, in <module>
    from dynatrace.main import Dynatrace
  File "/usr/local/lib/python3.8/site-packages/dynatrace/main.py", line 20, in <module>
    from dynatrace.configuration_v1.alerting_profiles import AlertingProfileService
ModuleNotFoundError: No module named 'dynatrace.configuration_v1'
```

The package published to pypi contains only top-level files in dynatrace folder (likely a packaging issue).

**Comment by dlopes7** [comment]
FYI @vduseev I think it is related to the attempt to remove tests

**Comment by vduseev** [comment]
Yep, that's it. The fix will be published in a few hours.
