### ISSUE TITLE
Retrieving problem details via api-client results in an error

### ISSUE THREAD

**Issue by rme2000** [dynatrace-oss/api-client-python#49]
I'm encountering an issue when trying to retrieve a problem using the api-client. Stacktrace:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/256/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/256/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/rene/.config/JetBrains/PyCharmCE2021.2/scratches/scratch.py", line 84, in <module>
    problem = get_problem_by_id('4323246839104750503_1636589220000V2')
  File "/home/rene/.config/JetBrains/PyCharmCE2021.2/scratches/scratch.py", line 70, in get_problem_by_id
    pd_problem = dt.problems.get(pid)
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/environment_v2/problems.py", line 73, in get
    return Problem(raw_element=response)
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/dynatrace_object.py", line 32, in __init__
    self._create_from_raw_data(raw_element)
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/environment_v2/problems.py", line 161, in _create_from_raw_data
    self.evidence_details: Optional[EvidenceDetails] = EvidenceDetails(raw_element=raw_element.get("evidenceDetails"))
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/dynatrace_object.py", line 32, in __init__
    self._create_from_raw_data(raw_element)
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/environment_v2/problems.py", line 200, in _create_from_raw_data
    [EventEvidence(raw_element=e) for e in raw_details if e.get("evidenceType") == EvidenceType.EVENT.value]
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/environment_v2/problems.py", line 200, in <listcomp>
    [EventEvidence(raw_element=e) for e in raw_details if e.get("evidenceType") == EvidenceType.EVENT.value]
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/dynatrace_object.py", line 32, in __init__
    self._create_from_raw_data(raw_element)
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/environment_v2/problems.py", line 220, in _create_from_raw_data
    super()._create_from_raw_data(raw_element)
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/environment_v2/problems.py", line 215, in _create_from_raw_data
    self.grouping_entity: Optional[EntityStub] = EntityStub(raw_element=raw_element.get("groupingEntity"))
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/dynatrace_object.py", line 32, in __init__
    self._create_from_raw_data(raw_element)
  File "/devPath/venv/lib/python3.8/site-packages/dynatrace/environment_v2/monitored_entities.py", line 201, in _create_from_raw_data
    self.entity_id: EntityId = EntityId(raw_element=raw_element["entityId"])
KeyError: 'entityId'
python-BaseException

Process finished with exit code 1
```

Failure happens here: 
https://github.com/dynatrace-oss/api-client-python/blob/main/dynatrace/environment_v2/problems.py#L161

Steps to reproduce
```
from dynatrace import Dynatrace

# initialize Dynatrace client
dt = Dynatrace(cfg['services']['dynatrace']['environment_url'], cfg['services']['dynatrace']['api_token'], retries=5, retry_delay_ms=1000)

def get_problem_by_id(pid: str):
    """
    Get details via problem_id
    :param pid (str) : problem_id string
    """
    pd_problem = dt.problems.get(pid)
    return pd_problem

problem = get_problem_by_id('<problem_id of existing problem>')
...
```

**Comment by dlopes7** [comment]
Fixed in 1.1.43, thanks for reporting
